<a href="https://colab.research.google.com/github/shahmeerkhan12/Machine-Learning/blob/main/neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

np.random.seed(0)

X = [[1, 2.1, 2, 2.2],
     [2, 1, 2.3, 1.2],
     [1, 2, 3, 2.5]]

class layer_dense:
  # for initialization specify the inputs_shape, and the number of the neurons( neurons can be any count)
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.1*np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output = np.dot(inputs,self.weights) + self.biases

layer1 = layer_dense(4,5)
layer2 = layer_dense(5,2)

layer1.forward(X)
layer2.forward(layer1.output)

print(layer1.output)
print()
print(layer2.output)





[[0.07339395 0.85908639 0.17316151 0.29562326 0.17385307]
 [0.32825362 0.68881268 0.33103156 0.50341013 0.4141685 ]
 [0.10758131 1.03983522 0.24462411 0.31821498 0.18851053]]

[[ 0.12282912 -0.06413357]
 [ 0.11666311 -0.02637691]
 [ 0.148296   -0.08397602]]
