In [1]:
import numpy as np

In [2]:
matrix = np.random.randint(10,size=(2,3,2))

In [3]:
matrix

array([[[5, 5],
        [2, 2],
        [3, 5]],

       [[4, 8],
        [9, 3],
        [6, 9]]], dtype=int32)

In [9]:
matrix[0] # access the first item of the 3D matrix which is a 2D matrix itself

array([[4, 8],
       [9, 3],
       [6, 9]], dtype=int32)

In [10]:
matrix[0][0] # access the first row of the first 2D matrix inside a 3D matrix

array([5, 5], dtype=int32)

In [11]:
matrix[0][0][0] # indvidual element of the 3D matrix

np.int32(5)

# slicing

In [13]:
matrix[0:1] # or matrix[:2] is also fine

array([[[5, 5],
        [2, 2],
        [3, 5]]], dtype=int32)

In [15]:
matrix[:2,:1] # the second arg :1 says that show me the first elements/rows of each of the two 2D matrix of the 3D matrix

array([[[5, 5]],

       [[4, 8]]], dtype=int32)

In [16]:
matrix[:2,:1,:1] # the 3rd arg say 10 show only first column of the matrix

array([[[5]],

       [[4]]], dtype=int32)