In [1]:
import numpy as np

**creating numpy arrays thru built-in functions**

In [4]:
# let we want to create and populate an array with all zeros
zeros = np.zeros((2,2))

In [5]:
zeros

array([[0., 0.],
       [0., 0.]])

In [7]:
# populate with ones
ones = np.ones((2,2))

In [8]:
ones

array([[1., 1.],
       [1., 1.]])

In [11]:
#populate all with a sequence of integers or float
# para start,stop,step
seq = np.arange(0,20,3)

In [10]:
seq

array([ 0,  3,  6,  9, 12, 15, 18])

In [13]:
# creatin random number array
r_arr =np.random.randint(10,30,size=(2,4)) 

In [15]:
r_arr.shape

(2, 4)

In [16]:
# creating between 0 and 1 exlcusive
btw_zero_one = np.random.rand(3,3)
btw_zero_one

array([[0.24045689, 0.93395265, 0.92780117],
       [0.12236212, 0.93440242, 0.91809713],
       [0.70882227, 0.06071136, 0.65420422]])