In [1]:
import numpy as np

In [2]:
matrix1 = np.random.randint(7,size=(3,5))

In [3]:
matrix1

array([[4, 0, 3, 2, 6],
       [5, 1, 2, 1, 3],
       [5, 4, 1, 6, 5]], dtype=int32)

In [4]:
matrix2 = np.random.randint(9,size = (3,5))

In [5]:
matrix2

array([[7, 8, 6, 4, 2],
       [7, 4, 4, 2, 3],
       [5, 2, 1, 3, 4]], dtype=int32)

**comparision operator**

In [6]:
# element wise comparision of two matrices
matrix1>matrix2

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [False,  True, False,  True,  True]])