In [1]:
import numpy as np

In [13]:
# create a random matrix of 5x6
matrix = np.random.rand(5,6)
new_matrix = np.round(matrix,2)
new_matrix

array([[0.79, 0.28, 0.31, 0.38, 0.57, 0.62],
       [0.32, 0.58, 0.89, 0.76, 0.65, 0.6 ],
       [0.96, 0.05, 0.36, 0.08, 0.72, 0.38],
       [0.86, 0.96, 0.79, 0.97, 0.1 , 0.08],
       [0.21, 0.75, 0.51, 0.95, 0.43, 0.96]])

In [15]:
# method 02 only for print options
float_formatter = "{:.2f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})
print(matrix)

[[0.79 0.28 0.31 0.38 0.57 0.62]
 [0.32 0.58 0.89 0.76 0.65 0.60]
 [0.96 0.05 0.36 0.08 0.72 0.38]
 [0.86 0.96 0.79 0.97 0.10 0.08]
 [0.21 0.75 0.51 0.95 0.43 0.96]]


In [18]:
# np.set_printoptions(formatter = None)   used to reformate the matrix output to original form
matrix

array([[0.7879957 , 0.28403893, 0.31433429, 0.37931588, 0.56550509,
        0.62450462],
       [0.3181425 , 0.58465824, 0.894332  , 0.760176  , 0.65261772,
        0.60326036],
       [0.96071186, 0.05274215, 0.3587591 , 0.0832376 , 0.71970925,
        0.37630153],
       [0.86284967, 0.96401434, 0.7855212 , 0.96851208, 0.0980467 ,
        0.08472455],
       [0.2096114 , 0.75118304, 0.5050264 , 0.95030839, 0.43154751,
        0.9624984 ]])

# turning array into dataFrame

In [19]:
import pandas as pd

In [26]:
# convert to dataframe
data = pd.DataFrame(matrix)

In [25]:
data

0         1         2         3         4         5
0  0.787996  0.284039  0.314334  0.379316  0.565505  0.624505
1  0.318143  0.584658  0.894332  0.760176  0.652618  0.603260
2  0.960712  0.052742  0.358759  0.083238  0.719709  0.376302
3  0.862850  0.964014  0.785521  0.968512  0.098047  0.084725
4  0.209611  0.751183  0.505026  0.950308  0.431548  0.962498