# dot product vs simple matrix multiplication

In [1]:
import numpy as np

In [18]:
np.random.seed(0)

In [26]:
m1 = np.random.randint(2,10,size=(3,4))

In [31]:
m2 = np.random.randint(5,11,size=(3,4))

In [32]:
m1,m2

(array([[6, 9, 8, 2],
        [2, 6, 4, 3],
        [8, 9, 9, 8]], dtype=int32),
 array([[ 5,  6, 10,  6],
        [10,  5,  6,  9],
        [ 8,  5,  8, 10]], dtype=int32))

**simple multiplication**

In [33]:
m1*m2

array([[30, 54, 80, 12],
       [20, 30, 24, 27],
       [64, 45, 72, 80]], dtype=int32)

**dot product**

In [35]:
m1.dot(m2.T) # u must ensure that the dimension match number of rows of m1 must match the col of m2 take transpose


array([[176, 171, 177],
       [104, 101, 108],
       [232, 251, 261]], dtype=int32)