# dot product vs simple matrix multiplication

In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [26]:
m1 = np.random.randint(2,10,size=(3,4))

In [31]:
m2 = np.random.randint(5,11,size=(3,4))

In [32]:
m1,m2

(array([[6, 9, 8, 2],
        [2, 6, 4, 3],
        [8, 9, 9, 8]], dtype=int32),
 array([[ 5,  6, 10,  6],
        [10,  5,  6,  9],
        [ 8,  5,  8, 10]], dtype=int32))

**simple multiplication**

In [33]:
m1*m2

array([[30, 54, 80, 12],
       [20, 30, 24, 27],
       [64, 45, 72, 80]], dtype=int32)

**dot product**

In [35]:
m1.dot(m2.T) # u must ensure that the dimension match number of rows of m1 must match the col of m2 take transpose


array([[176, 171, 177],
       [104, 101, 108],
       [232, 251, 261]], dtype=int32)

**reshape vs transpose**

In [3]:
# a reshape matrix method changes the dimensions of a matrix: for example
mat_1 = np.random.randint(2,9,size=(3,4))

In [7]:
mat_1

array([[6, 7, 2, 5],
       [5, 5, 3, 5],
       [7, 4, 6, 8]], dtype=int32)

In [9]:
np.shape(mat_1) # the original dimensions are 3*4; two 2D dimensional matrix

(3, 4)

In [16]:
mat_2_reshaped = mat_1.reshape(6,2,1)# now this is a 3Dimensional matrix

In [18]:
np.shape(mat_2_reshaped)

(6, 2, 1)