In [1]:
import numpy as np

In [13]:
np.random.seed(0)
matrix = np.random.randint(3,10,size=(5,3))

In [15]:
matrix

array([[7, 8, 3],
       [6, 6, 6],
       [4, 6, 8],
       [5, 7, 9],
       [3, 3, 7]], dtype=int32)

**lets sort the array**

In [4]:
np.sort(matrix) # sorts row-wise, axis = 1 by default

array([[3, 7, 8],
       [6, 6, 6],
       [4, 6, 8],
       [5, 7, 9],
       [3, 3, 7]], dtype=int32)

In [8]:
np.sort(matrix, axis=0) # sorts matrix by columns,

array([[3, 3, 3],
       [4, 6, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]], dtype=int32)

In [16]:
np.argmin(matrix) # retrun the index of the smallest item

np.int64(2)

In [17]:
np.argmax(matrix # return the index of the largest tiem)

np.int64(11)